a/urls.py
from django.urls import path, include
from .views import indexA, indexaaa,indexbbb,indexccc




urlpatterns = [
    path('',indexA,name="sampleA"),
    path('aaa/',indexaaa,name="sampleaaa"),
    path('bbb/',indexbbb),
    path('ccc/',indexccc),
]

djangomtv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main.views import index, test, sample
from a.views import indexA
from b.views import indexB, indexBdetail
# from c.views import indexC
from c.views import BlogList,BlogDetail
from d.views import indexD, testview,SignupView, LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('sample/',sample),
    path('testtest/',test),
    path('aa/',include('a.urls')),
    path('bb/',indexB),
    path('bb/<int:pk>/',indexBdetail),
    path('cc/',BlogList.as_view()),
    path('cc/<int:pk>/',BlogDetail.as_view()),
    path('dd/',indexD),
    path('dd/test/',testview),
    path('dd/signup/',SignupView.as_view()),
    path('dd/login/',LoginView.as_view()),
    path('dd/logout/',LogoutView.as_view()),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a/models.py
from django.db import models

# Create your models here.

b/models.py
from django.db import models
import random
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=100)
    # author : 인증 뒤에 언급을 해드리도록 하겠습니다.
    author=models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    contents = models.TextField()
    r=random.randint(1,10000)
    img= models.ImageField(upload_to=f"bb/%Y/%m/%d{r}",blank=True)# blank=true는 사용자가 업로드 입력하지 않아도 된다는 의미
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    modified_at=models.DateTimeField(auto_now=True,null=True)
    
    def __str__(self):
        return f'title:{self.title}, contents:{self.contents}'

c/models.py
from django.db import models

# Create your models here.

d/models.py
from django.db import models

# Create your models here.

e/models.py
from django.db import models

class Student(models.Model):
    number= models.IntegerField('학번')
    name = models.CharField('이름',max_length=20)
    major = models.ForeignKey(verbose_name="주전공", to='e.Department', on_delete=models.SET_NULL,null=True)
    friends= models.ManyToManyField(verbose_name="친구들",to='self',db_table='e_friendship',blank=True)
    
    def __str__(self):
        return self.name

class Department(models.Model):
    name=models.CharField("학과명",max_length=20)
    head=models.CharField("학과장",max_length=20)
    
    def __str__(self):
        return self.name

main/models.py
from django.db import models

class Notice(models.Model):
    title = models.CharField(max_length=100)
    likeCount = models.IntegerField()
    viewCount = models.IntegerField()
    contents = models.TextField()

    def __str__(self):
        return f'제목:{self.title}, 좋아요수:{self.likeCount}, 조회수:{self.viewCount}'

a/views.py
from django.shortcuts import render

def indexA(request):
    return render(request, 'indexA.html')
  
def indexaaa(request):
    return render(request, 'indexaaa.html')

def indexbbb(request):
    return render(request, 'indexbbb.html')

def indexccc(request):
    return render(request, 'indexccc.html')  

b/views.py
from django.shortcuts import render
from .models import Blog

def indexB(request):
    context= Blog.objects.all()
    return render(request, 'indexB.html', {'context':context})
    
def indexBdetail(request,pk):
    blog= Blog.objects.get(pk=pk)
    context={
        'blog':blog,
    }
    return render(request, 'indexBdetail.html',context)

c/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from b.models import Blog


#def indexC(request):
#    return render(request, 'indexC.html')

class BlogList(ListView):
    model = Blog
    template_name="indexC.html"
    ordering = "-pk"

class BlogDetail(DetailView):
    model=Blog
    template_name="indexCdetail.html"

d/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView as _LoginView, LogoutView as _LogoutView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required



def indexD(request):
    return render(request, 'indexD.html')

class SignupView(CreateView):
    template_name='signup.html'
    form_class = UserCreationForm
    model= get_user_model()
    
    def get_success_url(self):
        return '/dd/login/'
    
class LoginView(_LoginView):
    template_name='login.html'
    
    
class LogoutView(_LogoutView):
    template_name='logout.html'

class Profile(DetailView):
    pass 


@login_required
def testview(request):
    return render(request,'indexD.html')

e/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Notice


def index(request):
    print(request)
    print(type(request))
    print(dir(request))
    print('-----------')
    print(request.POST)
    return render(request, 'index.html')

def test(request):
    d={'name':'chanyong' ,'age':24}
    return JsonResponse(d)
    

def sample(request):
    d= Notice.objects.all()
    #d={'name':'hojun','age':10}
    #l=[100,200,300]
    return render(request,'sample.html',{'value':d})

a/templates/indexA.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world A</h1>
    <a href="{% url 'sampleaaa'%}">aaa로 이동</a>
</body>
</html>

a/templates/indexaaa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world aaa</h1>
    <a href="{% url 'sampleA'%}">aa로 이동</a>
</body>
</html>

b/templates/indexB.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <h1>hello world B</h1>
    <table class="table table-hover">
        <tr>
            <th>제목</th>
            <th>내용</th>
        </tr>
    {% for blog in context %}
        <tr>
            <td>
                <a href="/bb/{{blog.id}}/">{{blog.title}}</a>
            </td>
            <td>{{blog.contents}}</td>
        </tr>
    {% endfor %}
    </table>
    
</body>
</html>

b/templates/indexBdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <h1>hello world B</h1>
        {{blog.title}}
        {{blog.contents}}
        
    {% if blog.img %}
        <img src="{{blog.img.url}}",height="200px">
    {% endif %}
</body>
</html>

c/templates/indexC.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world C</h1>
    {% for i in blog_list %}
        <h1>{{i.title}}</h1>
        <p>{{i.contents}}</p> 
    {% endfor %}
</body>
</html>

c/templates/indexCdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world C</h1>
    
        <h1>{{blog.title}}</h1>
        <p>{{blog.contents}}</p> 
    
</body>
</html>

d/templates/indexD.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world D</h1>

    {% if user.is_authenticated %}
        <p>로그인 된 유저 :{{ user }}</p>
        <a href="/dd/logout/">로그아웃</a>
    {% else %}
        <a href="/dd/signup/">회원 가입</a>
        <a href="/dd/login/">로그인</a>
    {% endif %}
    
    
    
    
    
    
</body>
</html>

d/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
    
    <h1>로그인</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="로그인">        
    </form>
    
    <a href="/dd/">홈으로</a>
    <a href="/dd/signup/">회원가입</a>
    
</body>
</html>

d/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
    
    <h3>로그아웃 되었습니다.</h3>
    <a href="/dd/">홈으로</a>
    <a href="/dd/login/">로그인하기</a>
    
</body>
</html>

d/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
    
    <h1>회원가입</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="가입하기">        
    </form>
    
    
    
</body>
</html>

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world!!</h1>
    {% block body %}
    {% endblock body %}
    
    
    <p> footer </p>
</body>
</html>

main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world</h1>
    <form action="/" method="POST">
        {% csrf_token %}
        <input type="text" name="id"><br>
        <input type="password" name="pw"><br>
        <input type="submit" value="로그인">
    </form>
</body>
</html>

main/templates/sample.html
<h1>{{ value }}</h1>
<p>{{value.2.title}}</p>

{% for i in value %}
    <h1>{{ forloop.counter0 }}-{{ i.title }}</h1>
    <p>{{ i.contents }}</p>
    <p>{{ i.viewCount }}</p>
    {% if i.viewCount > 7 %}
        <p>뷰수가 많습니다.</p>
    {% elif i.viewCount > 5 %}
        <p>콘텐츠가 반응을 보이고 있습니다.</p>
    {% else %}
        <p>콘텐츠 홍보를 더 하셔야합니다. </p>
    {% endif %}
{% endfor %}

{% with value='hello world' %}
<h1>{{ value }}</h1>
{% endwith %}

{% load %}

{# hello world 주석입니다.#}
{% comment '주석' %}
{% for i in value %}
    <h1>{{ forloop.counter0 }}-{{ i.title }}</h1>
    <p>{{ i.contents }}</p>
    <p>{{ i.viewCount }}</p>
    {% if i.viewCount > 7 %}
        <p>뷰수가 많습니다.</p>
    {% elif i.viewCount > 5 %}
        <p>콘텐츠가 반응을 보이고 있습니다.</p>
    {% else %}
        <p>콘텐츠 홍보를 더 하셔야합니다. </p>
    {% endif %}
{% endfor %}
<p>hello world !!!! 여러줄 주석</p>
{% endcomment%}

{% lorem 3 p %}

It is {% now "jS F Y H:i" %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>hello world!!!!</h1>
    {% block body %}
    {% endblock body %}
    
    
    <p> footer </p>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <img src="{% static 'cat.jpg' %}" width ='200px' alt="">
    <form action="/" method="POST">
        {% csrf_token %}
        <input type="text" name="id"><br>
        <input type="password" name="pw"><br>
        <input type="submit" value="로그인">
    </form>
    <a href="https://insta-clone-kxbhe.run.goorm.io/testtest/">이동</a>
{% endblock body %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>test!!</h1>
</body>
</html>